language: php
sudo: false
before_install:
  - composer self-update
install:
  - composer update $COMPOSER_FLAGS
matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
      script: bin/phpunit --exclude-group perf
    - php: 7.0
      script: bin/phpunit --group perf
    - php: 7.0
      script: bin/phpunit --exclude-group perf --coverage-clover build/logs/clover.xml
      before_script:
        - mkdir -p build/logs
      after_script:
        - travis_retry php bin/coveralls -v
  fast_finish: true
